email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /SoM-ESPLab-DATASETS-CATALOG
url: "https://ou-esplab.github.io" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
loading: "Load in Python"

# Variables and Layout Settings

defaults:
  - scope:
      path: "assets"

collections:
  reanalysis:
    output: true
    permalink: /:path/index.html
  obs:
    output: true
    sub_dirs: [gridded,station,indices]
    permalink: /:path/index.html
  model:
    output: true
    permalink: /:path/index.html
    sub_dirs: [initialized,uninitialized]
  analysis:
    output: true
    permalink: /:path/index.html
  initialized:
    output: true
    permalink: /:path/index.html
    sub_dirs: [subx,nmme]
  subx:
    output: true
    permalink: /:path/index.html
    sub_dirs: [forecasts,hindcasts]
  nmme:
    output: true
    permalink: /:path/index.html
    sub_dirs: [forecasts,hindcasts]
  forecasts:
    output: true
    permalink: /:path/index.html
  hindcasts:
    output: true
    permalink: /:path/index.html
    

