email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /SoM-ESPLab-DATASETS-CATALOG
url: "https://ou-esplab.github.io" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
#loading: "Load in Python"

# Variables and Layout Settings

#defaults:
#  - scope:
#      path: "assets"

team_members:
  -
    name: "Sarah Becker"
    role: "project lead"
    start_date: "2016-02-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
